### ISSUE TITLE
Support state aliases

### ISSUE THREAD

**Issue by renkun-ken** [trulia/choroplethr#26]
Thanks for your great efforts made to this amazing package!

Would it be possible to support aliases of states so that it won't need data transformation before plotting if some state names appear as alias like USA to The United States of America?

In many data sources, state names are not quite usually recorded exactly in the official, full-length way. If some common aliases are supported, it would be much easier to use!

Thanks!

**Comment by louisb-trulia** [comment]
Support for choroplethr is moving to Ari's fork. Please file a new issue there if needed:
https://github.com/arilamstein/choroplethr
