### ISSUE TITLE
Links to vignettes in README.md does not match vignettes available at CRAN

### ISSUE THREAD

**Issue by stianlagstad** [trulia/choroplethr#35]
Links 4-10 in README.md does not match vignettes available at CRAN:
https://cran.r-project.org/web/packages/choroplethr/vignettes/

I see that the new vignettes are available in the vignettes folder here though.

**Comment by arilamstein** [comment]
Active development for choroplethr has moved to:

https://github.com/arilamstein/choroplethr

Can you please close this issue and test the links in that repo? If there
is a problem there, please create a new issue in that repo.

Thanks.

Ari

**Comment by stianlagstad** [comment]
I didn't realize - thanks!
