### ISSUE TITLE
set cutpoints for discretization?

### ISSUE THREAD

**Issue by vinhdizzo** [trulia/choroplethr#36]
Hi,

Is there an easy way to set cutpoints for filling the polygons?  I want to generate a series of choropleths, and would like to have the same pre-defined cutpoints for each so they are comparable.  Please let me know how this could be done.  Thanks!

**Comment by arilamstein** [comment]
Can you please close this issue and reopen it under
arilamstein/choproplethr? That is where active development is going on now.
