### ISSUE TITLE
User defined cutpoints for plotting

### ISSUE THREAD

**Issue by vinhdizzo** [trulia/choroplethr#37]
Hi,

Is there an easy way to set cutpoints for filling the polygons? I want to generate a series of choropleths, and would like to have the same pre-defined cutpoints for each so they are comparable. Please let me know how this could be done. Thanks!

**Comment by cbonsig** [comment]
stuck on this same issue. for examples: adding "breaks = seq(0,1,0.1)" causes the legend to disappear.
