### ISSUE TITLE
Germany: two federal states are missing

### ISSUE THREAD

**Issue by f34739** [trulia/choroplethr#40]
```
library(choroplethr)
library(choroplethrAdmin1)
library(ggplot2)
admin1_map("germany")
```

Output:

![rplot11](https://cloud.githubusercontent.com/assets/1590105/14776647/4db4a022-0ab7-11e6-8f13-84bc98210910.png)

Two federal states, Bremen and Berlin, are missing (approx. positions indicated by red circles).

Note that Bremen has a discontinuous territory: Bremerhaven (part of Bremen) is shown but Bremen itself is not.

**Comment by arilamstein** [comment]
Can you please close this issue and reopen it here:

https://github.com/arilamstein/choroplethrAdmin1

The project has moved, and I no longer have write access to this repo.

**Comment by f34739** [comment]
Ok. Reopened at https://github.com/arilamstein/choroplethrAdmin1/issues/3
