### ISSUE TITLE
Alaska and Hawaii colors are weird

### ISSUE THREAD

**Issue by rghertner** [trulia/choroplethr#42]
I'm making a US national choropleth using county level data. The colors for Alaska are miscolored for some reason. My R code for the map is:

```
cols<-c("white","#ffff00","#0000ff","#003400")
county_choropleth(dt)+scale_fill_manual(guide=FALSE,name="Relationship",values = cols,na.value="grey")
```

where data frame "dt" has two numeric columns, region and value. Region are the FIPS codes for counties (without leading zeros as its numeric). The colors are white, yellow, blue, and dark green. The values for Alaskan and Hawaiian counties are not out of the ordinary, but on the map they have weird shading that are not in the color palette. I've done this with different datasets and the same issue comes up. Here are two maps that use a different variable and the same color palette (same code above, just defining dt's value variable differently).
https://s26.postimg.org/ckntb25d5/levels_map.png
https://s26.postimg.org/w3sekf44p/test_map.png

Any clues as to what is going on here?

**Comment by arilamstein** [comment]
Please close this ticket and recreate it on arilamstein/choroplethr.
