### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by keevee09** [trulia/choroplethr#43]
The "9. Creating Your Own Maps" link is currently broken in your Readme.md.
It is pointing to:
https://cran.r-project.org/web/packages/choroplethr/vignettes/i-creating-your-own-maps.html
but should be pointing to:
https://cran.r-project.org/web/packages/choroplethr/vignettes/h-creating-your-own-maps.html

**Comment by arilamstein** [comment]
Please close this issue and PR - this repo is deprecated.

Instead verify whether the issue is still present under
arilamstein/choroplethr. If it is, then please recreate the issue and PR.
